LeStegii/server-software

- PROXIES.md
- SERVERS.md
Thank you for creating this list, I'm using it a lot!
> Added Flamecord and some [ABANDONNED] tags

- SERVERS.md
Add Mist (Paper Mohist) and GoldenForge (Paper Forge)
> Add Mist and GoldenForge

- SERVERS.md
This implements many softwares from this iceberg https://www.reddit.com/r/admincraft/comments/v2dfe6/the_server_software_iceberg/
> The 🧊Iceberg update

- BEDROCK.md
Add the vanilla bedrock server software to the BEDROCK.md list.
> Add vanilla bedrock

- SERVERS.md
Add [🧼Patina](https://github.com/UeberallGebannt/server-softwares/pull/23/commits/ceaf722ce55a6caa6792bd82d781ab8cf7957e6f)
Add [🧑🏻Mirai](https://github.com/UeberallGebannt/server-softwares/pull/23/commits/ceaf722ce55a6caa6792bd82d781ab8cf7957e6f)
Add [🚀Jettpack](https://github.com/UeberallGebannt/server-softwares/pull/23/commits/f6c0db96c83eb46090719bb022c27cfd7d11f76e)
Add [🏰EmpireCraft](https://github.com/UeberallGebannt/server-softwares/pull/23/commits/f6c0db96c83eb46090719bb022c27cfd7d11f76e)
Add [✂️Slice](https://github.com/UeberallGebannt/server-softwares/pull/23/commits/feb67b1b1e32a1311d76ea1ef8fac6e893a89eab)
Add [🧓Suki](https://github.com/UeberallGebannt/server-softwares/pull/23/commits/bbe0e596d4afdbf17be1a0d72d41aaa68abdc396)
Add …
> Add multiple softwars based on #17 by Lacosst0

- java/MODS+PLUGINS.md
- java/PLUGINS.md
Add all Hybrids softwares of [AnythingsMC Hybrids](https://anythingmc.xyz/server/info/lists/server_software/#plugins-and-mods-hybrids):
- Contigo
- NeptuneForge
- PFServer
- Lava
- AtomMC
- Hotpur
- Kettle
> Add all Hybrids of AnythingsMC

- bedrock/PLUGINS.md
- bedrock/VANILLA.md
[Add 🔴PowerNukkit(X)](https://github.com/UeberallGebannt/server-softwares/commit/037408d604e3e3304fe8ff3892edbd68a990ecc0)
[Add 📻JukeboxMC](https://github.com/UeberallGebannt/server-softwares/commit/48fea70449612697e89a1aa9d31f20e507d4d549)
[Add 🍃GoMint](https://github.com/UeberallGebannt/server-softwares/commit/fb645738bf2c847cf861774b3e4b387d2b1caaed)
[Add 🦋Dragonfly](https://github.com/UeberallGebannt/server-softwares/commit/771e65a0822977b7d8842905f7bbc269d992ae1a)
[Add ✳MiNET](https://github.com/UeberallGebannt/server-softwares/commit/31bf3b0a1ac538b5b205af1cac63fc6058b03cc9)
> Add multiple bedrock softwares (🔴PowerNukkit(X), 📻JukeboxMC, ...)

- java/MODS.md
> Add QuiltMC

- java/PROXIES.md
- lightfall
- gate
- BarelyAuthenticated
- DarkCord
- Flexagon
- Glymur
- MetaProxy
- VanillaCord
- wCord
- ElytraProxy
- JLilyPad
- GoLilyPad
> Add multiple Proxies of AnythingMC

- java/PLUGINS.md
> Add Leaves software

- java/PLUGINS.md
> Add Cheetah

- bedrock/PLUGINS.md
- java/PLUGINS.md
- java/VANILLA.md
Close #40 
Close #41 
Close #42 
Close #43 
Close #44 
And Flying Squid, Obsidian of #45
> Add more implementations

- OTHERS.md
- RECOMMEND.md
- bedrock/PLUGINS.md
- bedrock/PROXIES.md
- bedrock/README.md
- bedrock/VANILLA.md
- java/MODS+PLUGINS.md
- java/MODS.md
- java/PLUGINS.md
- java/PROXIES.md
- java/README.md
- java/VANILLA.md
- Add the missing points in the descriptions.
- Upgrade to 1.20.1.
- Move all software that have not had any commit in the last year to Inactive.
- Correct some typos.
- Fix some RECOMMEND.md links.
Close #50
> Update 1.20.1, inactive and more

- README.md
This PR adds a section for credits, currently including 
- @Razva, the inspiration for this project
- @JustDoom and anything-minecraft for providing many of the currently added softwares
- @TonimatasDEV for improving the list
- all the other contributors and developers who make this list possible in the first place.
I'm doing this as a PR in case that anyone wants to add something or has a suggestion for the credits.
> Add a section for credits

- java/MODS+PLUGINS.md
- java/PLUGINS.md
- java/VANILLA.md
Added softwares:
1. Granite
2. GoLandMc
3. Graphene
4. Hematite
5. EnchiladaSpigot
6. HOSE
7. MultiPaper
8. Hydrinity
9. NFT Worlds
10. NeptuneMod
11. Magma Maintained
Updated softwares:
- Magma
More servers of #24
> Add more softwares

- java/FOLIA.md
- java/MODS+PLUGINS.md
- java/MODS.md
- java/PLUGINS.md
- java/PROXIES.md
Update to minecraft 1.20.4
Close #71 
Close #70 
Close #69 
Close #68 
Close #67
> Requested softwares and update 1.20.4

- OTHERS.md
- java/PLUGINS.md
- java/PROXIES.md
- java/VANILLA.md
Fixes #77 
Fixes #76 
Fixes #75 
Fixes #73 
Fixes #79 
And add more softwares of #24 
- PaperMC-unpatch
- PaperBin
- Origami
- Lantern
- PartyCraft
- OpenSandbox
- PyMine
- Purplane
- Pukkit
- PopupMC
- Polaris
- Reflx
- Spout
- Spacecraft-GT
- Snowstorm
- Rush
- RealCraft
> Fix many issues and add more softwares

- RECOMMEND.md
- java/PROXIES.md
- java/README.md
Waterfall has reached end of life and will no longer receive updates. There is currently 2 prs open on the paper website and docs repos to document this.
> Waterfall reached EOL

- java/MODS+PLUGINS.md
> Correct typo and add Unsupported to Magma Maintained 1.20.1

- OTHERS.md
- RECOMMEND.md
- bedrock/PLUGINS.md
- bedrock/PROXIES.md
- bedrock/VANILLA.md
- java/FOLIA.md
- java/MODS+PLUGINS.md
- java/MODS.md
- java/PLUGINS.md
- java/PROXIES.md
- java/VANILLA.md
- replace "Fork: -" with "Fork: N/A"
- move colons inside bold formatting
- some other similar small adjustments
seems like there's been an error, because the fork lineage does not include the final result
https://github.com/LeStegii/server-softwares/blob/c22d5bfcadb93105e85ce3b94685d8eb095eb588/java/FOLIA.md?plain=1#L35-L38
instead of adding a footnote which users might not see with the list growing, the folia plugin compatability note now is at the top
> Some improvements

- RECOMMEND.md
Structuring every recommendation in the same way feels very sterile. Maybe going forward, with more versions appearing, this document could be reworked to feature tables for different use cases. For now, I've added some variation to make it more appealing when being read on a website.
Preview:
> add variation to recommendations

- .github/workflows/Build and Deploy to GitHub Pages.yaml
- README.md
*wow, so shiny 🫧*
**Some general remarks:**
- the workflow will create a `website` branch to host the files
- on each commit in this repo, the website will automatically update
- when that happens, the latest `mcss-frontend` version available will be used
- if there's an update to mcss-frontend that is desired, but not yet pulled because there's no recent commit, the workflow can be triggered manually
**The only things left to do:**
1. Merge
2. &nbsp;
3. &nbsp;
> Activate website 🔥

- bedrock/PLUGINS.md
- bedrock/PROXIES.md
- bedrock/VANILLA.md
- java/FOLIA.md
- java/MODS+PLUGINS.md
- java/MODS.md
- java/PLUGINS.md
- java/PROXIES.md
- java/VANILLA.md
> Update to 1.20.6 and fix forks/versions

- .github/workflows/Build and Deploy to GitHub Pages.yaml
- LOST.md
- OTHERS.md
- README.md
- RECOMMEND.md
- bedrock/PLUGINS.md
- bedrock/PROXIES.md
- bedrock/README.md
- bedrock/VANILLA.md
- java/FOLIA.md
- java/LIMBO.md
- java/LOST.md
- java/MODS+PLUGINS.md
- java/MODS.md
- java/PLUGINS.md
- java/PROXIES.md
- java/README.md
- java/VANILLA.md
Add all software of AnythingsMC, create the LOST category, change "softwares" to "software" and many fixes.
Closes #94 
Closes #92 
Closes #24 
Close #98 
**Add (25):**
- Bravo
- CraftBukkit++
- Creativity
- Crocus
- DytanicSpigot
- FeatherSpigot
- Fish
- hCraft 2
- Myne2
- NessusMS
- Nostalgia
- Quartz
- QuartzPowered
- Quesadilla
- RainForest
- RubberBukkit
- TridentSDK
- Rubbercord
- TableCloth
- Rainbow
- Wolf In a Bukkit
- Torch
- Bamboo
- Sink-MC
- JTE-Freebuild
> Fix some issues

- java/MODS+PLUGINS.md
MagmaMaintained has archived its whole organization.
> Archive MagmaMaintained

- LOST.md
- OTHERS.md
- bedrock/PLUGINS.md
- bedrock/PROXIES.md
- bedrock/VANILLA.md
- java/MODS+PLUGINS.md
- java/MODS.md
- java/PLUGINS.md
- java/PROXIES.md
- java/VANILLA.md
Continuation of #110 
I moved some to lost because their main page doesn't work.
> Finish add "Last commit" banners to all software
